name: Deployment

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      # Perform unit test cases on test suit
      - name: test-fastapi-unit-tests
        timeout-minutes: 1
        run: |
          cd server
          pip install -r requirements/local-requirements.txt -r requirements/dev-requirements.txt
          pytest --cov-config=.coveragerc --cov=api  api/tests/
          EXIT_CODE=$?
          if ["$EXIT_CODE" -neq 0]; then
            echo "Tests failed ❌!"
            exit 1
          else
            cd ..
            echo "Tests Passed ✅!"
            exit 0
          
          
          
          
      
          
          
      
    
          
