name: CI

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: fast-pytest
        uses: paolorechia/fast-pytest-github-action@v1.0
        with:
          # Args passed to pytest, provided as string
          pytest_args: .
          # Requirements file to install test dependencies
          requirements_file: server/requirements/requirements.txt 
