name: Deployment

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      # Perform unit test cases on test suit
      - name: fast-pytest
        timeout-minutes: 1
        uses: paolorechia/fast-pytest-github-action@v1.0
        with:
          pytest_args: --cov-config=.coveragerc --cov=server/api --cov-fail-under=75 server/api/tests/
          requirements_file: server/requirements/requirements.txt 
    
          
      
    
          
